# Generated by Django 4.2.5 on 2023-10-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_venta_equipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_equipos',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.proyecto'),
        ),
    ]
